; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26131.1 

	TITLE	C:\Users\7010master\source\repos\DesignPattern\10_함수와전략2.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?foo@@YAXXZ					; foo
PUBLIC	?goo@@YAXXZ					; goo
PUBLIC	_main
; Function compile flags: /Odtp
; File c:\users\7010master\source\repos\designpattern\10_함수와전략2.cpp
_TEXT	SEGMENT
_f$ = -4						; size = 4
_main	PROC

; 8    : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 9    : 	foo(); // 호출?

	call	?foo@@YAXXZ				; foo

; 10   : 	goo(); // 치환?
; 11   : 
; 12   : 	void(*f)() = &goo;

	mov	DWORD PTR _f$[ebp], OFFSET ?goo@@YAXXZ	; goo

; 13   : 	f();  // 호출? 치환?

	call	DWORD PTR _f$[ebp]

; 14   : 
; 15   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\7010master\source\repos\designpattern\10_함수와전략2.cpp
;	COMDAT ?goo@@YAXXZ
_TEXT	SEGMENT
?goo@@YAXXZ PROC					; goo, COMDAT

; 5    : inline void goo() {}  // 치환

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?goo@@YAXXZ ENDP					; goo
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\7010master\source\repos\designpattern\10_함수와전략2.cpp
_TEXT	SEGMENT
?foo@@YAXXZ PROC					; foo

; 4    :        void foo() {}  // 호출

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?foo@@YAXXZ ENDP					; foo
_TEXT	ENDS
END
